### PR TITLE
fix(bind): allow serialization of Some(_) and None values (as the inner value and NULL respectively)

### LINKED ISSUE #119: Unable to serialize `Option<_>` bind
Trying to write

```rust
client
  .query("SELECT ?fields FROM table WHERE nullable_field = ?")
  .bind(None)
```

fails at runtime with:

`invalid param: invalid SQL: invalid argument: serialize_none is unsupported`

The pattern of having nullable binds is quite common in server-side applications so I would have expected `Option<_>` support in binds somewhere (or maybe I missed it).

### PR DESCRIPTION
**Pull request by v3xro**
Fixes #119

### CODE REVIEW

File: src/sql/mod.rs [hunk 1]
```diff
@@ -184,20 +184,27 @@ mod tests {
         );
     }
 
+    #[test]
+    fn option_as_null() {
+        let mut sql = SqlBuilder::new("SELECT 1 FROM test WHERE a = ?");
```
Comment (loyd) [inline src/sql/mod.rs:189]: It's a possible behavior and quite logical, but it's not an "optional filter" as declared in https://github.com/ClickHouse/clickhouse.rs/issues/119. In the case of a missing filter, the whole `a = ..` should be omitted.

@slvrtrn what do you think?

Comment (loyd) [reply src/sql/mod.rs:189]: Anyway, `None` as `NULL` is very logical but not related to "optional filters" in any possible way.

File: src/sql/ser.rs [hunk 2]
```diff
@@ -340,8 +345,8 @@ mod tests {
     fn it_fails_on_unsupported() {
         let mut out = String::new();
         assert!(write_arg(&mut out, &std::collections::HashMap::<u32, u32>::new()).is_err());
-        assert!(write_arg(&mut out, &None::<u32>).is_err());
-        assert!(write_arg(&mut out, &Some(42)).is_err());
+        assert!(write_arg(&mut out, &None::<u32>).is_ok());
+        assert!(write_arg(&mut out, &Some(42)).is_ok());
```
Comment (loyd) [inline src/sql/ser.rs:349]: The test is named "it FAILS on unsupported" =)

Comment (loyd) [inline src/sql/ser.rs:349]: The test is named "it FAILS on unsupported" =)

**Review by loyd — CHANGES_REQUESTED** [review]

File: src/sql/mod.rs (hunk 1 above)
Comment (slvrtrn) [reply src/sql/mod.rs:189]: If we take "optional filter" literally, it is more of an ORM feature (and, in my opinion, does not belong in this client).

However, I think that the right interpretation in this case is just binding None as NULL, and this is correct, so we should just merge this.

Comment (v3xro) [reply src/sql/mod.rs:189]: Yes, I didn't mean to suggest that "optional filters" should be provided by this library (though in theory you could do that) - more that this pattern is fairly common and also fairly easy to implement once you can bind None/Some(_)

Comment (loyd) [reply src/sql/mod.rs:189]: > it is more of an ORM feature

It's not precisely ORM (because there is no object-relation mapping), but it requires some sort of SQL generator, yep.

> more that this pattern is fairly common

Yep, I have in production custom generator:
```
fn make_predicate(params: FilterParams) -> impl Predicate<Row = SomeRow> {
    // Describe columns that will be used in filters.
    // It generates structs named according to columns.
    columns! {
        SomeRow;
        robot_id,           u32,    RobotId;
        base_asset_id,      u32,    AssetId;
        quote_asset_id,     u32,    AssetId;
    }

    let filter = |p: FieldsFilterParams| {
        robot_id.eq_any(p.robots)
            & base_asset_id.eq_any(p.base_assets)
            & quote_asset_id.eq_any(p.quote_assets)
            & (base_asset_id.eq_any(p.assets.clone()) | quote_asset_id.eq_any(p.assets))
    };

    filter(params.include) & !filter(params.exclude)
}
```
Exactly to cover filters.

Not an area of responsibility of this crate anyway.

**Review by loyd — APPROVED** [review]

**Comment by loyd** [comment]
Merged. Thanks for your contribution!
